query Movies($where: MovieWhere, $ratedByUserWhere2: UserWhere, $ratedConnectionWhere2: UserRatedConnectionWhere) {
  movies(where: $where) {
    title
    year
    imdbRating
    imageUrl
    plot
    similarMovies {
      title
      imdbRating
      imageUrl
    }
    genres {
      name
    }
    actors {
      name
    }
    director {
      name
    }
    ratedByUser(where: $ratedByUserWhere2) {
      name
      ratedConnection(where: $ratedConnectionWhere2) {
        edges {
          rating
        }
      }
    }
  }
}
