query userQueries($where: UserWhere) {
  users(where: $where) {
    name
    recommendedMovies {
      title
      imdbRating
      imageUrl
    }
    recommendedByGenres {
      title
      imdbRating
      imageUrl
    }
    liked_genres {
      name
    }
  }
}